server:
  port: 7997
spring:
  application:
    name: sys-base-data
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zxxr
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
      com:
        zachary:
          base:
            sysbasedata:
              mapper: debug
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: user-secret-8888
#      access-token-uri: http://localhost:7998/oauth/token
#    authorization:
#      check-token-access: http://localhost:7998/oauth/check_token
    resource:
      jwt:
        key-uri: http://localhost:7998/oauth/token_key
        key-value: zachary