server:
  port: 8081
spring:
  application:
    name: monitor
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka,http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always